#!/bin/bash

# taken from https://gist.github.com/rossf7/664dc1eb02f514993c7215d37058965c
# File needs to be called /hooks/build relative to the Dockerfile.
# $IMAGE_NAME var is injected into the build so the tag is correct.

# used for labeling the automated build but fails.. still "latest" is used each time..
# might give a try to this source: https://artsy.github.io/blog/2018/09/10/Dockerhub-Stamping-Commits/

echo "Build hook running"
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             -t $IMAGE_NAME .
